@startuml Диаграмма контейнеров - Интеграция ставок с кол-центрами
!include <C4/C4_Container>

title Диаграмма контейнеров - Интеграция ставок с кол-центрами

Person(оператор, "Оператор кол-центра", "Сотрудник кол-центра, консультирующий клиентов")
Person(оператор2, "Оператор внешнего кол-центра", "Сотрудник внешнего кол-центра, консультирующий клиентов")

System_Boundary(система_банка, "Банковская система") {
    Container(абс, "АБС", "Delphi, Oracle", "Основная банковская система")
    Container(сервис_ставок, "Сервис ставок", "Java Spring Boot", "Централизованный сервис управления ставками")
    Container(sftp_сервер, "SFTP-сервер", "Linux/SSH", "Сервер для передачи файлов")
}

System(кц_банка, "Система кол-центра", "Java Spring Boot", "Система внешнего вендора для кол-центра")
System(кц_партнера, "Система партнера", "Внешняя система", "Система партнерского кол-центра")


Rel(оператор, кц_банка, "Использует интерфейс для просмотра ставок", "UI")
Rel(оператор2, кц_партнера, "Использует партнерскую систему для просмотра ставок", "UI")

Rel(кц_банка, абс, "Запрашивает актуальные ставки", "REST API")
Rel(абс,сервис_ставок, "Получает/обновляет данные о ставках", "DB API/Web Service")

Rel(сервис_ставок, sftp_сервер, "Генерирует и загружает файлы с актуальными ставками", "SFTP")
Rel(кц_партнера, sftp_сервер, "Скачивает файлы с актуальными ставками", "SFTP")

@enduml